version: "3"
services:
  react:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["pnpm", "run", "test"]
