name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t my-docker-image:${{ github.sha }} -f dockerfile/Dockerfile.dev ./
      - run: docker run -e CI=true my-docker-image:${{ github.sha }} pnpm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "docker-react-app"
          environment_name: "Docker-react-app-env-1"
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-017821386653
          region: "ap-northeast-2"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
