name: CI/CD with Docker

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Run Test
      - name: Run Test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run test

      # 3. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-docker-image:${{ github.sha }} -f dockerfile/Dockerfile.prod ./

      # 5. Push Docker Image to Registry
      - name: Push Docker Image
        # run: |
        #   docker tag my-docker-image:${{ github.sha }} juneryu/react-docker-practice-ryu9663:latest
        #   docker push juneryu/react-docker-practice-ryu9663:latest
        run: |
          docker build -t juneryu/react-docker-practice-ryu9663:latest dockerfile/Dockerfile.prod ./
          docker push juneryu/react-docker-practice-ryu9663:latest
